### ISSUE TITLE
.yml localizations seem to bleed into other locales in copycopter

### ISSUE THREAD

**Issue by kwerle** [copycopter/copycopter-ruby-client#33]
We have a bunch of required fields and use the rails-i18n gem to get localizations of "has to be filled out", "must be larger/smaller than...", etc.  And that works great.

But copycopter seems to be bleeding the from one locale to another.  I'm digging into the problem, and it seems to come from the client and it seems to matter which language you get the error message in first.  

I _think_ it goes something like:
- Submit a form for a model with an error in German
- View that same model in an index or show page in English

``` yml
en:
  activerecord:
    errors:
      models:
        book:
          attributes:
            title:
              blank: muss ausgefüllt werden
```

All the translations for that model show up, but it is getting the German error message
